### PR TITLE
Fixes #16 Improved handling of incorrect user input

### LINKED ISSUE #16: Improve handling of incorrect user input
Current solution does not handle `ArgumentNullException` and `OverflowException` (in fact, it handles only `FormatException`).
image

It's better to use `int.TryParse`, which allows to have more control over the user input. `try-catch` is not necessary - it makes the code less comprehensible.

### PR DESCRIPTION
**Pull request by javorske**

### CODE REVIEW

File: Calculator/Program.cs [hunk 1]
```diff
@@ -11,20 +11,21 @@ class Program
...
-                    Console.WriteLine("0. Quit.\n");
-                try
+                Console.WriteLine("Choose operation:");
+                Console.WriteLine("1. Add.");
+                Console.WriteLine("2. Subtract.");
+                Console.WriteLine("3. Multiply.");
+                Console.WriteLine("4. Divide.");
+                Console.WriteLine("0. Quit.\n");
+                
+                if (Int32.TryParse(Console.ReadLine(), out int caseChoice))
```
Comment (kjaworski) [inline Calculator/Program.cs]: 1. Use `int` instead of `Int32`.
2. Add variable for value returned by `TryParse` - too many things are happening in one line and it's hard to read.

File: Calculator/Program.cs [hunk 2]
```diff
@@ -48,13 +49,12 @@ static void Main(string[] args)
                     }
                     mathOperations.MathOperation();
                 }
-                catch(FormatException)
+                else
                 {
-                    Console.WriteLine("No option selected or wrong character entered.");
+                    Console.WriteLine("No option selected or wrong character entered");
```
Comment (kjaworski) [inline Calculator/Program.cs]: Can `SwitchDefault()` be used here? Of course it should be renamed, because `SwitchDefault()` doesn't switch anything, it just prints something to the console.

**Review by kjaworski — CHANGES_REQUESTED** [review]

**Comment by javorske** [comment]
Done in 2e94875

**Review by kjaworski — APPROVED** [review]
